from enum import Enum


class InternalEvent(str, Enum):
    USER_MESSAGE = 'USER_MESSAGE'
    SCREEN_CAPTURED = 'SCREEN_CAPTURED'
    OCR_COMPLETE = 'OCR_COMPLETE'
    MEMORY_RETRIEVED = 'MEMORY_RETRIEVED'
    TOOL_EXECUTED = 'TOOL_EXECUTED'
    STREAM_STARTED = 'STREAM_STARTED'
    STREAM_COMPLETED = 'STREAM_COMPLETED'
    WORKFLOW_CANCELLED = 'WORKFLOW_CANCELLED'
